apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:          # stringData takes plain text, k8s base64-encodes it for you
  DB_USER: "admin"
  DB_PASSWORD: "sup3rs3cret"
  API_KEY: "ak_live_12345"
