apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0
          args: ["-text=hello from web", "-listen=:8080"]
          ports:
            - containerPort: 8080
